In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('dataset_cleaned.csv')

# **Exploratory Data Analysis**

In [3]:
df.head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,573347,21803,CHRISTMAS TREE STAR DECORATION,1,30-10-11 12:26,0.42,13137,United Kingdom,0.42
1,576236,22505,MEMO BOARD COTTAGE DESIGN,1,14-11-11 13:31,4.95,13755,United Kingdom,4.95
2,541839,22435,SET OF 9 HEART SHAPED BALLOONS,1,23-01-11 11:15,1.25,17769,United Kingdom,1.25
3,579675,84931B,BLUE SCOTTIE DOG W FLOWER PATTERN,12,30-11-11 13:08,2.55,15654,United Kingdom,30.60
4,578541,21931,JUMBO STORAGE BAG SUKI,3,24-11-11 15:01,2.08,14277,France,6.24

In [4]:
df.tail(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
14797,565129,23206,LUNCH BAG APPLE DESIGN,5,01-09-11 12:41,1.65,15719,United Kingdom,8.25
14798,555746,21849,SILVER DIAMANTE PEN IN GIFT BOX,1,07-06-11 10:55,4.95,14606,United Kingdom,4.95
14799,558565,21982,PACK OF 12 SUKI TISSUES,12,30-06-11 13:58,0.29,14803,United Kingdom,3.48
14800,554348,48187,DOORMAT NEW ENGLAND,2,24-05-11 8:49,7.95,13523,United Kingdom,15.90
14801,549874,21175,GIN + TONIC DIET METAL SIGN,2,12-04-11 15:23,2.55,16919,United Kingdom,5.10

In [5]:
df.shape

(14802, 9)

In [6]:
df.size

133218

In [7]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country', 'Revenue'],
      dtype='str')

In [8]:
df.describe()

           InvoiceNo      Quantity     UnitPrice    CustomerID       Revenue
count   14802.000000  14802.000000  14802.000000  14802.000000  14802.000000
mean   560632.527902     12.851169      3.185599  15275.512431     22.371088
std     13091.827407     43.232228     15.823118   1729.230257     76.107490
min    536370.000000      1.000000      0.000000  12347.000000      0.000000
25%    549250.250000      2.000000      1.250000  13871.000000      4.680000
50%    561708.000000      6.000000      1.950000  15129.500000     11.900000
75%    572126.000000     12.000000      3.750000  16804.000000     19.800000
max    581587.000000   1900.000000   1526.760000  18287.000000   3828.000000

In [9]:
for i in df.columns:
    print(df[i].value_counts(),i)
    print('-----------------------------')

InvoiceNo
579196    32
567183    21
576339    21
575607    19
547063    18
          ..
581469     1
570799     1
566778     1
560942     1
536394     1
Name: count, Length: 8262, dtype: int64 InvoiceNo
-----------------------------
StockCode
22423     70
85123A    66
85099B    60
POST      59
23203     49
          ..
84950      1
84706F     1
21378      1
21821      1
22525      1
Name: count, Length: 2519, dtype: int64 StockCode
-----------------------------
Description
REGENCY CAKESTAND 3 TIER              70
WHITE HANGING HEART T-LIGHT HOLDER    66
JUMBO BAG RED RETROSPOT               60
POSTAGE                               59
LUNCH BAG SPACEBOY DESIGN             49
                                      ..
SMALL TALL CAMPHOR WOOD TOADSTOOL      1
GLITTER STAR GARLAND WITH BELLS        1
ANIMALS AND NATURE WALL ART            1
72 CAKE CASES VINTAGE CHRISTMAS        1
CHILDRENS GARDEN GLOVES PINK           1
Name: count, Length: 2582, dtype: int64 Description
-----------------------------
Quantity
1      2740
12     2299
2      2153
6      1407
4      1156
       ...
44        1
56        1
43        1
960       1
38        1
Name: count, Length: 90, dtype: int64 Quantity
-----------------------------
InvoiceDate
28-11-11 15:54    32
14-11-11 15:27    21
10-11-11 12:37    19
20-03-11 13:33    18
18-09-11 15:32    18
                  ..
08-12-11 19:28     1
12-10-11 12:31     1
15-09-11 10:02     1
22-07-11 11:31     1
01-12-10 10:39     1
Name: count, Length: 8017, dtype: int64 InvoiceDate
-----------------------------
UnitPrice
1.25      1703
1.65      1378
2.95       967
0.85       959
0.42       795
          ...
16.65        1
6.67         1
3.90         1
295.00       1
2.39         1
Name: count, Length: 187, dtype: int64 UnitPrice
-----------------------------
CustomerID
17841    260
14911    218
14096    192
12748    166
14606    107
        ...
15057      1
14522      1
13611      1
17031      1
17299      1
Name: count, Length: 3049, dtype: int64 CustomerID
-----------------------------
Country
United Kingdom          13107
Germany                   387
France                    333
EIRE                      276
Spain                      89
Netherlands                81
Belgium                    75
Switzerland                62
Australia                  56
Portugal                   51
Norway                     42
Finland                    36
Channel Islands            26
Cyprus                     24
Italy                      24
Austria                    18
Japan                      17
Denmark                    14
Poland                     13
Sweden                     10
Israel                      9
Unspecified                 9
Malta                       8
USA                         7
Singapore                   7
Canada                      5
RSA                         4
Iceland                     3
Greece                      3
United Arab Emirates        2
Lithuania                   2
European Community          1
Brazil                      1
Name: count, dtype: int64 Country
-----------------------------
Revenue
15.00     764
19.80     401
17.70     345
16.50     321
10.20     287
         ...
295.00      1
10.05       1
28.00       1
229.44      1
112.00      1
Name: count, Length: 871, dtype: int64 Revenue
-----------------------------

In [10]:
for i in df.columns:
  print(df[i].unique(),i)
  print('*'*100)

[573347 576236 541839 ... 566778 560942 536394] InvoiceNo
****************************************************************************************************
<StringArray>
[ '21803',  '22505',  '22435', '84931B',  '21931',  '22568',  '21987',
  '21260',  '21058',  '22090',
 ...
 '90063A',  '23121',  '23410', '84952C', '75013B',  '84950', '84706F',
  '21378',  '21821',  '22525']
Length: 2519, dtype: str StockCode
****************************************************************************************************
<StringArray>
[   'CHRISTMAS TREE STAR DECORATION',         'MEMO BOARD COTTAGE DESIGN',
    'SET OF 9 HEART SHAPED BALLOONS', 'BLUE SCOTTIE DOG W FLOWER PATTERN',
            'JUMBO STORAGE BAG SUKI',             'FELTCRAFT CUSHION OWL',
        'PACK OF 6 SKULL PAPER CUPS',                     'FIRST AID TIN',
            'PARTY INVITES WOODLAND',           'PAPER BUNTING RETROSPOT',
 ...
      'CURIO CABINET LINEN AND LACE',   'MIRROR LOVE BIRD T-LIGHT HOLDER',
      'STRING OF 8 BUTTERFLIES,PINK',    'ASSORTED COLOUR T-LIGHT HOLDER',
             'RED PEONY TABLE CLOCK', 'SMALL TALL CAMPHOR WOOD TOADSTOOL',
   'GLITTER STAR GARLAND WITH BELLS',       'ANIMALS AND NATURE WALL ART',
   '72 CAKE CASES VINTAGE CHRISTMAS',      'CHILDRENS GARDEN GLOVES PINK']
Length: 2582, dtype: str Description
****************************************************************************************************
[   1   12    3    4    6  108   80    8  120    2   18   36   10   24
   32   16   25   48  600    5   30  400   40  320   96   50   72    9
  288   21   20  100  200   14  720    7  360  864  125  144   11   60
  432  240  384  128   13 1440  300  192   15  774 1878   42 1008  250
  800   19   34 1200  160   22  216  480  270 1900   64  256   84   17
  180   90   33  132  204  168  500  576   26   75   35  252  291  150
   28   44   56   43  960   38] Quantity
****************************************************************************************************
<StringArray>
['30-10-11 12:26', '14-11-11 13:31', '23-01-11 11:15', '30-11-11 13:08',
 '24-11-11 15:01', '10-10-11 11:37', '06-04-11 10:07', '17-03-11 15:34',
 '02-09-11 13:15', '22-09-11 16:58',
 ...
 '23-01-11 12:19', '11-09-11 13:22', '07-11-11 12:27', '21-10-11 11:18',
 '09-01-11 14:12', '08-12-11 19:28', '12-10-11 12:31', '15-09-11 10:02',
 '22-07-11 11:31', '01-12-10 10:39']
Length: 8017, dtype: str InvoiceDate
****************************************************************************************************
[4.20000e-01 4.95000e+00 1.25000e+00 2.55000e+00 2.08000e+00 3.75000e+00
 6.50000e-01 3.25000e+00 8.50000e-01 2.95000e+00 2.10000e+00 8.00000e-02
 1.65000e+00 1.88000e+00 3.49500e+01 9.95000e+00 5.95000e+00 8.50000e+00
 7.95000e+00 1.27500e+01 4.25000e+00 1.95000e+00 1.45000e+00 8.25000e+00
 2.89000e+00 3.39000e+00 3.90000e-01 2.10000e-01 2.49000e+00 4.15000e+00
 5.50000e-01 2.90000e-01 1.49500e+01 6.75000e+00 2.40000e-01 1.79000e+00
 8.95000e+00 1.25000e+02 9.50000e-01 6.95000e+00 1.09500e+01 2.46000e+00
 7.50000e+00 3.95000e+00 1.85000e+00 1.25000e+01 1.49000e+00 1.69000e+00
 1.50000e+01 7.20000e-01 1.20000e-01 2.25000e+00 1.06000e+00 1.69500e+01
 7.90000e-01 8.30000e-01 6.25000e+00 3.40000e-01 3.29000e+00 5.75000e+00
 1.07900e+01 2.50000e-01 3.45000e+00 3.60000e-01 1.63000e+00 8.15000e+00
 3.44000e+00 1.90000e-01 1.66300e+01 5.00000e+01 1.04000e+00 4.13000e+00
 2.83020e+02 7.05000e+00 1.41300e+01 4.65000e+00 7.50000e-01 4.00000e+01
 4.96000e+00 3.20000e-01 4.04600e+01 5.79000e+00 1.80000e+01 5.90000e-01
 1.00000e-01 7.46000e+00 5.45000e+00 6.20000e-01 1.00000e+00 1.24000e+00
 1.70000e-01 1.27000e+00 8.20000e-01 1.99500e+01 6.30000e-01 2.70000e-01
 7.45000e+00 7.08000e+00 1.04000e+01 1.57900e+01 5.99500e+01 1.19500e+01
 1.74000e+00 3.35000e+00 2.49500e+01 1.08000e+00 8.49000e+00 1.55000e+00
 4.58000e+00 7.65000e+00 1.48000e+00 7.90000e+00 2.31000e+00 6.35000e+00
 2.91300e+01 3.80000e-01 6.63000e+00 3.50000e+00 1.06500e+01 1.80000e-01
 7.40000e-01 1.31600e+01 6.65000e+00 3.20000e+00 2.99500e+01 1.59500e+01
 1.00000e+01 6.45000e+00 5.55000e+00 2.17000e+00 3.50000e+01 1.07500e+01
 6.40000e-01 1.70000e+00 1.90000e+00 1.10000e+00 6.38000e+00 1.75000e+00
 8.29000e+00 1.32900e+01 5.39000e+00 2.08340e+02 1.65000e+02 2.80000e+01
 1.40000e-01 9.00000e-02 4.80000e+00 5.49000e+00 1.60000e-01 2.75600e+02
 1.16300e+01 2.50000e+01 3.59500e+01 1.80000e+00 0.00000e+00 4.00000e-02
 5.00000e-01 2.08000e+01 3.00000e-01 6.00000e-02 2.12000e+00 2.75000e+00
 1.46000e+00 1.66000e+00 7.25000e+00 2.19500e+01 6.36000e+00 3.50000e+02
 1.53000e+00 3.88000e+00 2.26000e+00 3.99500e+01 3.81000e+00 1.99600e+01
 7.85000e+00 8.78550e+02 4.00000e-01 1.24600e+01 5.66000e+00 2.66000e+00
 1.52676e+03 2.20000e-01 1.66500e+01 6.67000e+00 3.90000e+00 2.95000e+02
 2.39000e+00] UnitPrice
****************************************************************************************************
[13137 13755 17769 ... 13611 17031 17299] CustomerID
****************************************************************************************************
<StringArray>
[      'United Kingdom',               'France',            'Australia',
              'Germany',              'Belgium',                'Spain',
             'Portugal',          'Netherlands',               'Cyprus',
               'Poland',                 'EIRE',      'Channel Islands',
          'Switzerland', 'United Arab Emirates',                'Japan',
               'Norway',              'Finland',               'Canada',
               'Israel',                'Italy',          'Unspecified',
            'Lithuania',               'Sweden',                'Malta',
              'Austria',              'Denmark',                  'USA',
            'Singapore',   'European Community',              'Iceland',
                  'RSA',               'Greece',               'Brazil']
Length: 33, dtype: str Country
****************************************************************************************************
[4.20000e-01 4.95000e+00 1.25000e+00 3.06000e+01 6.24000e+00 1.50000e+01
 3.90000e+00 1.95000e+01 1.02000e+01 3.54000e+01 2.52000e+01 8.64000e+00
 3.96000e+02 1.32000e+01 2.25600e+02 3.30000e+00 6.29100e+02 6.60000e+00
 9.90000e+00 1.19400e+02 1.53000e+01 1.19000e+01 2.55000e+00 1.78500e+01
 3.40000e+01 1.65000e+00 1.25000e+01 4.16000e+00 5.90000e+00 3.18000e+01
 2.04000e+01 7.65000e+00 8.50000e-01 5.94000e+01 1.27500e+01 4.25000e+00
 4.64000e+01 8.25000e+00 5.10000e+00 1.70000e+00 1.77000e+01 5.78000e+00
 1.65000e+01 1.22040e+02 2.00000e+01 3.90000e-01 5.25000e+00 8.40000e-01
 2.97000e+01 3.40000e+00 5.95000e+00 1.49400e+01 3.32000e+01 8.50000e+00
 1.73400e+01 2.08000e+01 4.68000e+01 1.98000e+01 3.00000e+01 1.39200e+01
 1.19600e+02 2.70000e+01 1.44000e+02 9.95000e+01 4.08000e+01 1.26000e+00
 2.95000e+00 1.70000e+01 1.74000e+01 5.20000e+00 4.20000e+00 2.10000e+00
 2.31200e+01 1.26000e+01 6.24000e+01 1.66000e+01 9.36000e+00 2.08000e+00
 1.24800e+01 7.16000e+02 3.96000e+01 1.79000e+01 8.85000e+00 1.05000e+01
 1.25000e+02 5.80000e+01 2.90000e+00 8.13600e+01 5.28000e+02 2.55000e+01
 3.80000e+00 1.16000e+01 3.75000e+00 5.00000e+00 7.50000e+00 4.50000e+01
 2.34000e+01 5.80000e+00 1.39000e+01 1.31400e+02 4.15000e+00 5.85000e+00
 9.75000e+00 1.59000e+01 2.34000e+00 4.92000e+00 9.95000e+00 1.02000e+02
 1.56000e+00 1.45000e+00 2.50000e+00 5.04000e+00 6.96000e+00 1.18000e+01
 3.95000e+00 3.12000e+01 8.30000e+00 2.89000e+00 1.77600e+02 1.05000e+02
 1.99000e+01 1.00800e+01 2.22000e+02 2.49600e+01 9.00000e+01 1.30000e+00
 1.12500e+01 1.35000e+01 7.80000e+00 3.75000e+01 1.48500e+01 6.50000e-01
 7.95000e+00 7.90000e+00 5.96000e+00 9.50000e-01 4.77000e+01 5.97600e+01
 4.05600e+01 2.25000e+01 1.17000e+01 9.50000e+00 3.57000e+01 1.95000e+00
 2.07360e+02 1.00000e+01 1.50000e+02 1.44000e+01 2.25000e+00 2.37600e+02
 1.03950e+02 1.56000e+01 3.90000e+01 2.50000e+01 2.52000e+00 7.63200e+01
 3.39000e+01 7.90000e-01 7.20000e+01 8.30000e-01 6.25000e+00 6.80000e+01
 1.39200e+02 5.50000e-01 7.14000e+01 7.02000e+01 1.22400e+02 1.49500e+01
 1.01400e+01 4.98000e+00 6.58000e+00 1.65000e+02 2.34000e+02 9.48000e+00
 7.80000e-01 3.25000e+00 3.45000e+01 7.65000e+01 3.82500e+01 5.10000e+01
 1.78800e+01 1.49000e+00 2.37000e+00 1.07900e+01 2.36000e+01 4.35000e+00
 4.13000e+01 7.70000e+00 6.64000e+00 9.00000e+02 5.31000e+01 1.58000e+01
 9.96000e+00 8.70000e-01 4.16000e+01 1.90000e+00 6.75000e+00 8.75000e+00
 2.19000e+01 2.10000e+01 1.47500e+01 3.30000e+01 4.68000e+00 1.22040e+03
 1.64500e+01 1.69500e+01 2.10000e-01 2.16000e+02 8.28000e+01 5.04000e+01
 2.26800e+02 3.38000e+00 2.98800e+01 4.72000e+01 2.38000e+01 2.47500e+01
 1.87500e+01 9.96000e+01 8.30000e+01 1.04000e+01 4.95000e+01 4.89000e+00
 6.00000e+01 4.98000e+01 9.78000e+01 5.50400e+01 1.82400e+01 5.90000e+01
 2.98500e+01 8.32000e+00 6.12000e+01 2.88000e+00 2.04000e+02 5.50000e+00
 1.80000e+02 7.56000e+00 8.16000e+01 2.26800e+01 8.97000e+01 2.02800e+01
 6.95000e+00 1.59200e+02 1.66300e+01 5.00000e+01 3.32000e+00 1.49760e+02
 8.70000e+00 1.36000e+01 1.63000e+01 2.62800e+02 3.98000e+01 1.65200e+01
 2.99000e+01 2.01600e+01 6.05000e+00 1.45000e+02 2.83020e+02 5.64000e+01
 1.51200e+01 1.41300e+01 7.50000e+01 2.37000e+01 5.70000e-01 1.74000e+00
 2.95000e+01 1.68000e+00 9.30000e+00 7.47000e+00 2.73000e+00 1.89600e+01
 6.80000e+00 9.00000e+00 1.15600e+01 1.17000e+00 1.35200e+01 1.79000e+02
 2.49000e+01 3.58000e+02 1.39500e+01 1.72200e+01 2.31000e+01 2.00000e+02
 3.48000e+00 2.46000e+00 6.72000e+00 4.96000e+00 7.56000e+01 1.36000e+02
 1.38240e+02 9.98400e+01 1.00800e+02 4.04600e+01 5.79000e+00 2.60000e+00
 7.02000e+00 1.99200e+01 1.19200e+01 6.76000e+01 2.80800e+01 1.09500e+01
 2.11200e+02 5.40000e+01 1.60000e+02 9.13000e+00 3.36000e+00 4.74000e+00
 9.21600e+01 4.56000e+00 1.73700e+01 4.16000e+02 1.80000e+01 1.30000e+01
 9.44000e+00 6.84000e+00 1.87200e+01 8.20600e+01 8.95000e+00 3.50400e+02
 5.45000e+00 3.57600e+01 1.27200e+02 2.14500e+01 7.44000e+00 2.88000e+01
 2.70000e+02 2.97500e+01 6.00000e+00 9.87000e+00 3.58000e+01 1.45600e+01
 2.68500e+01 8.11200e+01 4.90500e+01 1.35000e+02 9.25000e+01 4.88160e+02
 2.44800e+02 1.47000e+01 4.45500e+01 5.85000e+01 1.15000e+01 8.40000e+00
 8.59200e+01 7.25000e+00 2.08500e+01 3.04800e+01 9.81000e+01 2.79000e+01
 2.06500e+01 6.75000e+01 8.20000e+00 2.28000e+01 7.92000e+01 3.99000e+01
 1.99500e+01 1.10000e+00 1.62500e+01 1.72800e+02 1.24500e+01 3.02400e+01
 8.88000e+01 5.18400e+01 5.68800e+01 5.08500e+01 4.13000e+00 1.78800e+02
 2.20000e+00 5.80000e-01 6.96000e+01 7.08000e+01 2.90000e-01 4.00000e+01
 1.69000e+00 1.48000e+01 3.15800e+01 5.99500e+01 1.19500e+01 6.22500e+01
 1.63500e+01 1.74000e+02 2.85000e+00 2.28800e+01 3.35000e+00 3.20000e-01
 2.94000e+00 2.44080e+02 2.16000e+01 6.76000e+00 3.46800e+01 7.48500e+01
 1.23000e+01 2.39000e+01 7.60000e+00 9.67500e+02 1.01700e+02 2.02824e+03
 1.85000e+02 1.52820e+02 6.30000e+00 8.25000e+01 2.70400e+01 4.65000e+00
 6.04800e+01 1.37400e+03 3.60000e+01 5.76000e+00 2.78400e+01 2.07500e+02
 7.46000e+00 1.37500e+01 5.37000e+02 1.40400e+01 2.32000e+01 5.25000e+01
 1.18440e+02 1.63000e+00 1.68000e+01 5.75000e+00 6.60000e+01 3.56400e+02
 7.16000e+01 2.38500e+01 3.29000e+00 1.18400e+01 4.74000e+01 1.53600e+01
 2.18000e+01 2.32848e+03 2.13120e+02 2.64000e+01 1.27000e+01 2.78000e+01
 1.18500e+01 2.03000e+01 9.84000e+00 2.88000e+02 6.91200e+01 1.18800e+02
 8.32000e+01 2.30300e+01 1.27500e+02 2.98000e+00 2.61000e+01 6.50000e+00
 6.93600e+01 2.91300e+01 1.66000e+00 5.37000e+01 5.98000e+01 4.03200e+01
 6.63000e+00 1.58000e+00 1.57500e+02 4.55000e+00 1.57900e+01 1.69000e+01
 9.12000e+00 2.70600e+01 1.79280e+02 3.48000e+01 2.22000e+01 3.05280e+02
 1.06500e+01 4.32000e+00 3.16000e+01 7.10400e+01 2.49000e+00 4.02000e+01
 3.28500e+03 5.60500e+01 1.24800e+02 2.89000e+01 1.75200e+02 9.18000e+01
 5.20200e+01 8.94000e+01 6.09000e+00 1.31600e+01 1.50000e+00 5.04000e+02
 3.15000e+01 2.29500e+01 4.29600e+01 2.66000e+01 4.48500e+01 4.08000e+02
 1.36500e+01 1.23900e+01 8.45000e+00 1.38000e+01 9.52000e+01 3.95000e+01
 1.36800e+01 1.45000e+01 8.50000e+01 2.30000e+01 1.26000e+02 4.00000e+02
 1.66800e+02 2.21400e+01 4.47000e+00 7.96000e+01 2.28000e+00 3.26000e+00
 2.08800e+02 3.78000e+01 4.50000e+00 1.86000e+01 8.70000e+01 3.30000e+02
 3.19000e+01 3.16800e+02 3.17900e+01 1.27200e+01 6.66000e+01 2.49500e+01
 1.53600e+02 5.99000e+01 5.07000e+00 1.83600e+02 1.55000e+00 6.72000e+01
 3.00000e+00 1.20000e-01 8.92500e+01 2.60000e+01 1.97500e+01 1.62720e+02
 1.29000e+01 7.95000e+01 5.94000e+02 5.56500e+01 1.85900e+01 1.69800e+01
 1.69500e+02 1.89000e+00 6.70000e+00 2.98400e+01 4.05000e+01 7.42500e+01
 3.16000e+00 1.03750e+02 7.08000e+00 2.66400e+02 1.05000e+00 1.01760e+02
 1.42200e+01 7.38000e+00 3.47400e+01 6.36000e+00 2.54400e+01 2.40000e+02
 2.01600e+02 1.07400e+02 3.47200e+01 1.09000e+01 7.89600e+01 7.98000e+00
 1.13400e+02 1.59500e+01 4.14000e+01 7.50000e-01 1.36800e+03 1.41600e+02
 3.50000e+01 6.64000e+01 1.30500e+01 1.14000e+01 8.76000e+01 7.62000e+01
 3.69000e+01 1.14100e+02 2.02500e+01 1.15800e+01 2.15000e+01 1.08160e+02
 2.03520e+02 2.08600e+01 2.54000e+01 6.37500e+01 4.28400e+02 6.20000e-01
 1.22880e+02 1.10000e+01 1.32800e+01 1.63200e+02 3.80000e+02 4.59000e+01
 3.37500e+01 1.32000e+02 8.67000e+00 2.09700e+02 3.82800e+03 2.89500e+01
 2.07500e+01 1.75000e+02 8.06400e+01 6.30000e-01 1.84320e+02 9.91200e+01
 6.57000e+01 1.28880e+02 1.00000e+02 5.22000e+01 6.35000e+00 4.42500e+01
 1.20000e+02 4.24000e+01 1.11000e+02 2.14560e+02 3.55200e+02 7.60000e-01
 1.49400e+02 8.29000e+00 1.32900e+01 3.51000e+01 6.36000e+01 6.46800e+01
 8.10000e+01 4.29000e+00 2.59200e+01 2.32500e+01 1.24000e+01 3.98400e+01
 1.01500e+01 1.04000e+02 3.12500e+01 1.08480e+02 7.14000e+00 1.52640e+02
 9.48000e+01 2.08340e+02 3.78000e+00 3.46500e+01 2.75000e+00 8.40000e+01
 2.97000e+02 1.63800e+02 2.46000e+01 1.21680e+02 1.53000e+02 1.66400e+01
 6.26400e+01 6.45000e+00 7.80000e+01 3.06000e+02 7.11000e+00 5.56800e+01
 2.72000e+01 8.91000e+02 2.12500e+01 1.30500e+02 5.40800e+01 3.94800e+01
 1.04040e+02 5.42400e+01 2.27500e+01 1.55520e+02 2.72500e+01 9.90000e-01
 8.26000e+00 1.42800e+02 1.44500e+01 5.76000e+02 2.17500e+01 5.49000e+00
 9.16000e+02 8.15000e+00 3.51000e+00 2.09000e+00 8.00000e-01 5.51200e+02
 5.15520e+02 7.45000e+00 1.16300e+01 6.43500e+01 5.46000e+00 6.99000e+02
 3.80800e+02 4.12500e+01 2.12000e+01 3.27000e+01 1.90000e-01 1.11000e+01
 3.59500e+01 1.08000e+01 1.99680e+02 6.32000e+00 6.20000e+00 4.76000e+01
 1.08000e+02 9.79200e+02 2.52000e+02 1.89000e+01 3.12000e+00 8.96400e+01
 7.98000e+01 1.03500e+01 4.99200e+01 2.84400e+01 5.79600e+02 3.45600e+01
 0.00000e+00 4.00000e+00 2.29000e+03 4.78400e+02 1.13400e+01 1.44000e+00
 2.40000e+01 2.90000e+01 2.10240e+03 9.36000e+01 2.02300e+01 4.14720e+02
 9.90000e+01 2.00000e+00 2.65500e+01 1.80000e+00 2.28960e+02 3.90000e+02
 1.72800e+01 1.21600e+01 9.60000e+00 1.48400e+01 2.20000e+01 1.46000e+00
 3.77000e+01 2.32500e+02 1.76400e+01 6.90000e+00 5.70000e+00 6.32000e+01
 1.33000e+01 3.23700e+01 1.14000e+00 2.36600e+01 3.48000e+02 3.07200e+01
 2.76480e+02 2.19500e+01 1.15200e+02 1.35680e+02 8.06400e+02 2.75000e+02
 3.50000e+02 1.58400e+02 1.57500e+01 4.80000e-01 4.25000e+01 4.94700e+01
 2.17500e+02 4.36000e+01 3.10000e+00 5.90000e-01 7.34400e+01 3.72000e+01
 2.52800e+01 2.79360e+02 1.16000e+00 1.34400e+01 3.02400e+02 1.18300e+01
 2.68800e+01 2.29950e+02 1.33200e+02 9.16000e+01 7.38000e+01 9.49200e+01
 1.13760e+02 1.01400e+02 6.38000e+01 2.26000e+02 4.22500e+01 1.00000e+00
 2.01000e+01 1.92000e+01 5.76000e+01 7.50000e+02 3.99500e+01 4.17600e+01
 2.25000e+02 6.14400e+01 5.81000e+00 3.60000e-01 4.75000e+00 2.13360e+02
 1.87500e+02 1.98000e+02 8.34000e+01 3.74400e+01 5.97000e+01 7.47000e+01
 9.35000e+00 2.14200e+02 2.49000e+02 4.60000e+01 4.57200e+01 3.00000e-01
 1.99600e+01 2.03000e+00 1.62000e+02 1.57000e+01 1.40400e+02 1.52000e+00
 8.78550e+02 1.19000e+02 4.89000e+01 1.04400e+02 3.75000e+02 5.37500e+01
 8.94000e+00 1.01250e+02 5.35500e+01 1.33000e+02 4.17000e+01 9.54000e+01
 1.18000e+00 2.34720e+02 6.30000e+01 2.72000e+02 3.84000e+02 4.72000e+00
 8.17500e+01 5.60000e+01 1.25020e+02 1.64000e+01 5.95000e+01 8.50000e+02
 1.46700e+01 1.24600e+01 4.06800e+01 1.57920e+02 2.40900e+02 3.17500e+01
 3.99000e+00 7.85000e+00 5.47500e+01 2.08800e+01 6.79200e+02 8.00000e+01
 2.39400e+01 8.42400e+01 1.02400e+03 3.83500e+01 5.58000e+01 1.90500e+01
 7.11000e+01 7.96800e+01 2.07900e+02 1.17000e+02 1.52676e+03 9.71100e+01
 7.25000e+01 7.34400e+02 5.44000e+02 5.28000e+00 1.51200e+02 1.66500e+01
 3.25000e+01 8.00400e+01 7.05000e+00 6.25000e+01 4.40000e+00 4.47000e+01
 4.68000e+02 2.14800e+02 2.95000e+02 1.00500e+01 2.80000e+01 2.29440e+02
 1.12000e+02] Revenue
****************************************************************************************************

**Checking DataTypes of Different Columns**

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14802 entries, 0 to 14801
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    14802 non-null  int64
 1   StockCode    14802 non-null  str
 2   Description  14802 non-null  str
 3   Quantity     14802 non-null  int64
 4   InvoiceDate  14802 non-null  str
 5   UnitPrice    14802 non-null  float64
 6   CustomerID   14802 non-null  int64
 7   Country      14802 non-null  str
 8   Revenue      14802 non-null  float64
dtypes: float64(2), int64(3), str(4)
memory usage: 1.0 MB

**Checking For Null Values**

In [12]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
Revenue        0
dtype: int64

**Checking for Duplicates**

In [13]:
df.duplicated().sum()

np.int64(15)

**Removing Duplicates**

In [14]:
df.drop_duplicates(inplace=True)

In [15]:
df.duplicated().sum()

np.int64(0)

**Converting Datatype of Invoice Date**

In [16]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], format='%d-%m-%y %H:%M')

In [17]:
df.info()

<class 'pandas.DataFrame'>
Index: 14787 entries, 0 to 14801
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    14787 non-null  int64
 1   StockCode    14787 non-null  str
 2   Description  14787 non-null  str
 3   Quantity     14787 non-null  int64
 4   InvoiceDate  14787 non-null  datetime64[us]
 5   UnitPrice    14787 non-null  float64
 6   CustomerID   14787 non-null  int64
 7   Country      14787 non-null  str
 8   Revenue      14787 non-null  float64
dtypes: datetime64[us](1), float64(2), int64(3), str(3)
memory usage: 1.1 MB

# **Cohort Analysis**

**Creating Invoice Month**

In [18]:
df['InvoiceMonth'] = df['InvoiceDate'].dt.to_period('M')

In [19]:
df.head(1)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,InvoiceMonth
0,573347,21803,CHRISTMAS TREE STAR DECORATION,1,2011-10-30 12:26:00,0.42,13137,United Kingdom,0.42,2011-10

**Creating Cohort Month**

In [22]:
cohort_month = (
    df.groupby('CustomerID')['InvoiceMonth']
      .min()
)

In [24]:
df['CohortMonth'] = df['CustomerID'].map(cohort_month)

In [25]:
df.head(1)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,InvoiceMonth,CohortMonth
0,573347,21803,CHRISTMAS TREE STAR DECORATION,1,2011-10-30 12:26:00,0.42,13137,United Kingdom,0.42,2011-10,2011-02

**Creating Cohort Index**

In [26]:
invoice_year = df['InvoiceMonth'].dt.year
cohort_year = df['CohortMonth'].dt.year

In [27]:
invoice_month = df['InvoiceMonth'].dt.month
cohort_month = df['CohortMonth'].dt.month

In [29]:
df['CohortIndex'] = (
    (invoice_year - cohort_year) * 12
    + (invoice_month - cohort_month)
)

In [32]:
df.head(4)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,InvoiceMonth,CohortMonth,CohortIndex
0,573347,21803,CHRISTMAS TREE STAR DECORATION,1,2011-10-30 12:26:00,0.42,13137,United Kingdom,0.42,2011-10,2011-02,8
1,576236,22505,MEMO BOARD COTTAGE DESIGN,1,2011-11-14 13:31:00,4.95,13755,United Kingdom,4.95,2011-11,2011-10,1
2,541839,22435,SET OF 9 HEART SHAPED BALLOONS,1,2011-01-23 11:15:00,1.25,17769,United Kingdom,1.25,2011-01,2011-01,0
3,579675,84931B,BLUE SCOTTIE DOG W FLOWER PATTERN,12,2011-11-30 13:08:00,2.55,15654,United Kingdom,30.60,2011-11,2011-11,0